### PR TITLE
Use interface for Triggers instead of a struct.

### PR DESCRIPTION
**Pull request by JReyLBC**
These changes have the merged changes from @flexd, and some of my own.
I thought since Triggers are defined purely in terms of their behavior, it might be better to implement them as an interface. I updated the samples, examples, and readme to reflect the changes.

Your thoughts?

### CODE REVIEW

**Comment by whyrusleeping** [comment]
I like the idea, but i think if we do something like this, that we should keep the old struct, and just let it implement the interface as well. My primary goal with the struct was to allow for declaration of triggers on the spot, without having to formally define them anywhere.

**Comment by flexd** [comment]
I disagree. Having this as an interface in this form gains us nothing over the struct, other than less clear syntax. I was thinking for a while maybe it would be nice to use an interface ala. http.Handler. But if we did, we would have to implement some kind of message routing based on incoming IRC data to avoid executing every handler for every line.

That would make the bot a lot more complicated, so I ended up not liking this way of doing it.

**Comment by JReyLBC** [comment]
My thoughts were based off the idea that using an interface, I can make each struct that implements the trigger interface have its own state (and manage its own state).  I also have loose coupling between triggers and their implementation, which could make it easier to add triggers imho. I suppose I could do this by making each struct have its own trigger member variable, but then I'd be tightly coupled with the bot.

**Comment by whyrusleeping** [comment]
mostly agreed with @flexd, the only advantage i see is that allowing the user to have their own struct allows them to have triggers that maintain state, which could have some interesting applications. It does however introduce a good deal of extra complexity

**Comment by JReyLBC** [comment]
Ok. No worries. I'll close this pull request.

**Comment by whyrusleeping** [comment]
@JReyLBC thanks anyways though :) I'm really happy to have people around and helping out. Do you have any feedback on the other open PR?

**Comment by JReyLBC** [comment]
@whyrusleeping - not yet, and you're welcome. Thanks for sharing this awesome project :)
I'm still becoming familiar with hellabot's code, while using it as a library for my company's internal IRC bot. 
I'll keep you posted though.

**Pull request closed without merging**
