### PR TITLE
Adding reading configuration from JSON file

### PR DESCRIPTION
**Pull request by mudler**
Hi,

First of all thank you for this project, i find it very educational and also well structured. :+1: 
For my personal uses, i found myself comfy to load configurations from JSON (the changes also adds the possibility to automatically join channels after connection) . I don't know if actually could be useful, but worth a try, or at least could be handy for someone else searching thru the pull request :)

Cheers

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Hey! Thanks for the interest, i'm glad you like the code :smile: This change looks good, the only thing I would do a little differently is separate the config loading from the construction code, make your `NewConnection` function accept a config struct, and then make a function that loads and returns the config, this way people can create the config struct in code and pass it in. Fairly minor change, and I can do it if you'd like.

Again, thanks for the PR :)

**Comment by mudler** [comment]
@whyrusleeping you are welcome :)

Doing the modifications right now! :+1:

**Comment by mudler** [comment]
I don't know if method names could be called in another way, of course feel free to touch and edit this as much as you like. Thanks :beers:

**Comment by whyrusleeping** [comment]
awesome, thanks!

**Pull request merged**
