### PR TITLE
Add Oracle Solaris Support for session hijacking

### PR DESCRIPTION
**Pull request by ugjka**
Tested on official Solaris 11 image in Virtualbox

No love for Plan9 and Windows though

### CODE REVIEW

**Comment by flexd** [comment]
Why do you keep closing your issues? I'm not around 24/7, I had not even seen this before you closed it.

**Comment by ugjka** [comment]
Sorry, I'm schizophrenic

**Comment by ugjka** [comment]
basically you add `solaris` to recon_unix build constraints and `,!solaris` to recon_dummy

**Comment by ugjka** [comment]
it is pure unix so no special knobs needed

**Pull request closed without merging**
