### PR TITLE
Stop invoking triggers after a message is consumed

### LINKED ISSUE #24: Action return value does nothing
I expected returning `true` from an `Action` function would prevent further triggers from firing, but it doesn't seem to do anything.

### PR DESCRIPTION
**Pull request by icholy**
Fix #24

### CODE REVIEW

**Comment by flexd** [comment]
Thanks! 👍 Sorry this has taken such a long time, I don't use hellabot any more. Not sure if @whyrusleeping  does either

**Comment by icholy** [comment]
@whyrusleeping  @flexd I'm willing to help with maintenance if you two aren't active on here anymore.

**Comment by whyrusleeping** [comment]
@icholy Hey, yeah. I'm not using this anymore either, if you're down to help out with maintenance, then by all means! (i'll add you as a collab)

**Comment by icholy** [comment]
Dope

**Pull request merged**
